{% set name = "xcube-cci" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dcs4cop/xcube-cci/archive/v{{ version }}.tar.gz
  sha256: 9b929f2d364acdd87c2279a58fc070a42458775a28a3cb1cd446687f50cd43e3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - xcube >=0.6.2
    - aiohttp >=3.6
    - nest-asyncio >=1.3
    - lxml >=4.5
    - pydap >=3.2

test:
  imports:
    - xcube_cci

about:
  summary: xcube plugin for the ESA CCI Open Data Portal
  home: https://github.com/dcs4cop/xcube-cci
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube-cci is an xcube plugin that allows generating data cubes from the ESA CCI Open Data Portal.
  doc_url: https://github.com/dcs4cop/xcube-cci/blob/master/README.md
  dev_url: https://github.com/dcs4cop/xcube-cci

extra:
  recipe-maintainers:
    - pont-us
    - dzelge
    - TonioF
    - forman
    - AliceBalfanz
